# Generated by Django 2.0.13 on 2019-08-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='words_of_wisdom',
            field=models.TextField(default='happy'),
        ),
    ]
